data_processing:
  test_size: 0.2
  random_state: 42

experiments:
  RandomForest Baseline:
    model_type: RandomForest
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    class_weight: true
    random_state: 42

  RandomForest Tuned:
    model_type: RandomForest
    n_estimators: 117
    max_depth: 15
    min_samples_split: 3
    min_samples_leaf: 3
    class_weight: true
    random_state: 42

  GradientBoosting Baseline:
    model_type: GradientBoosting
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5
    subsample: 0.8
    random_state: 42

  GradientBoosting Tuned:
    model_type: GradientBoosting
    n_estimators: 465
    learning_rate: 0.10000661955341474
    max_depth: 8
    subsample: 0.8695194175199982
    random_state: 42